#!/bin/bash
# generate-api-docs.sh - Generate API reference documentation from Jarvis tool definitions
#
# Usage: ./scripts/generate-api-docs.sh [output_file]
#
# This script extracts tool definitions from handlers/server.go and generates
# a markdown API reference document.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_FILE="${1:-$ROOT_DIR/docs/API_REFERENCE.md}"
SERVER_GO="$ROOT_DIR/Jarvis/handlers/server.go"

# Ensure docs directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate header
cat > "$OUTPUT_FILE" << 'HEADER'
# Jarvis API Reference

> Auto-generated from tool definitions in `handlers/server.go`

This document provides a complete reference for all Jarvis MCP tools.

---

HEADER

# Parse server.go and extract tool definitions
current_category=""
in_tool=0
tool_name=""
tool_desc=""
params=""

while IFS= read -r line; do
    # Check for category comments
    if [[ "$line" =~ //[[:space:]]*(System\ Management|Server\ Management|Profile\ Management|Client\ Management|Configuration|Project\ Analysis|System\ Bootstrap|Server\ Sharing) ]]; then
        new_cat="${BASH_REMATCH[1]}"
        if [[ "$new_cat" != "$current_category" ]]; then
            if [[ -n "$current_category" ]]; then
                echo "" >> "$OUTPUT_FILE"
            fi
            current_category="$new_cat"
            echo "## $current_category" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
        fi
    fi

    # Check for tool definition start
    if [[ "$line" =~ mcp\.NewTool\(\"([^\"]+)\" ]]; then
        tool_name="${BASH_REMATCH[1]}"
        tool_desc=""
        params=""
        in_tool=1
    fi

    # Check for description
    if [[ $in_tool -eq 1 ]] && [[ "$line" =~ mcp\.WithDescription\(\"([^\"]+)\"\) ]]; then
        tool_desc="${BASH_REMATCH[1]}"
    fi

    # Check for string parameter
    if [[ $in_tool -eq 1 ]] && [[ "$line" =~ mcp\.WithString\(\"([^\"]+)\" ]]; then
        param_name="${BASH_REMATCH[1]}"
        params="$params|$param_name|string"
    fi

    # Check for boolean parameter
    if [[ $in_tool -eq 1 ]] && [[ "$line" =~ mcp\.WithBoolean\(\"([^\"]+)\" ]]; then
        param_name="${BASH_REMATCH[1]}"
        params="$params|$param_name|boolean"
    fi

    # Check for tool definition end (Handler assignment)
    if [[ $in_tool -eq 1 ]] && [[ "$line" =~ Handler:[[:space:]]*h\. ]]; then
        # Output tool documentation
        echo "### \`$tool_name\`" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"
        echo "$tool_desc" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        if [[ -n "$params" ]]; then
            echo "**Parameters:**" >> "$OUTPUT_FILE"
            echo "" >> "$OUTPUT_FILE"
            echo "| Name | Type |" >> "$OUTPUT_FILE"
            echo "|:-----|:-----|" >> "$OUTPUT_FILE"
            # Parse params
            IFS='|' read -ra PARAM_ARRAY <<< "$params"
            i=1
            while [[ $i -lt ${#PARAM_ARRAY[@]} ]]; do
                pname="${PARAM_ARRAY[$i]}"
                ptype="${PARAM_ARRAY[$((i+1))]}"
                echo "| \`$pname\` | $ptype |" >> "$OUTPUT_FILE"
                i=$((i+2))
            done
            echo "" >> "$OUTPUT_FILE"
        fi

        echo "---" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        in_tool=0
        tool_name=""
        tool_desc=""
        params=""
    fi
done < "$SERVER_GO"

# Add footer
cat >> "$OUTPUT_FILE" << 'FOOTER'

## Tool Categories Summary

| Category | Description |
|:---------|:------------|
| System Management | Health checks, bootstrapping, service management |
| Server Management | Install, uninstall, search, configure MCP servers |
| Profile Management | Create and manage composable tool profiles |
| Client Management | Configure AI clients (Claude, Cursor, etc.) |
| Configuration | Manage global settings and migrations |
| Project Analysis | Analyze projects and apply DevOps stacks |
| System Bootstrap | System initialization and infrastructure |
| Server Sharing | Share servers via secure tunnels |

---

*Generated by `scripts/generate-api-docs.sh`*
FOOTER

echo "API reference generated: $OUTPUT_FILE"
